import type { Metadata } from "next";
import { Inter, Playfair_Display, Geist_Mono } from "next/font/google";
import SocialCorner from "./components/SocialCorner";
import WhatsAppFloat from "./components/WhatsAppFloat";
import "./globals.css";

  {/* import Navbar from './components/Navbar'; */}
import Footer from "./components/Footer";
import CustomCursor from "./components/CustomCursor";
import LeadCaptureTabs from "./components/LeadCaptureTabs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
    
          {/*   <Navbar /> */}
        {children}
        <LeadCaptureTabs />
        <Footer/>
        {/* <SocialCorner/> */}
        <WhatsAppFloat/>
        </body>
    </html>
  );
}
